// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQaylLpYzjs2TyOBGyIRI9CfqliMhKmqo',
    appId: '1:464068075288:web:486e06aeae4d01dbd7886d',
    messagingSenderId: '464068075288',
    projectId: 'fir-connection-b7b26',
    authDomain: 'fir-connection-b7b26.firebaseapp.com',
    storageBucket: 'fir-connection-b7b26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDenifKXT_2dpQNAzjtJfZ9TGp0W4kKF0I',
    appId: '1:464068075288:android:66aceae4993e6d45d7886d',
    messagingSenderId: '464068075288',
    projectId: 'fir-connection-b7b26',
    storageBucket: 'fir-connection-b7b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWZnMCDuqOakGS-ASrUtXn8MC_QYhppIY',
    appId: '1:464068075288:ios:89c155c30cf2563ed7886d',
    messagingSenderId: '464068075288',
    projectId: 'fir-connection-b7b26',
    storageBucket: 'fir-connection-b7b26.appspot.com',
    androidClientId: '464068075288-7ckstmii89vrfke8kdqmvpj7hll4od7s.apps.googleusercontent.com',
    iosClientId: '464068075288-f2tcicfudujfp1fmug8beftlk13i80hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWZnMCDuqOakGS-ASrUtXn8MC_QYhppIY',
    appId: '1:464068075288:ios:89c155c30cf2563ed7886d',
    messagingSenderId: '464068075288',
    projectId: 'fir-connection-b7b26',
    storageBucket: 'fir-connection-b7b26.appspot.com',
    androidClientId: '464068075288-7ckstmii89vrfke8kdqmvpj7hll4od7s.apps.googleusercontent.com',
    iosClientId: '464068075288-f2tcicfudujfp1fmug8beftlk13i80hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
